name: Publish package
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v3
            - name: Node ğŸ–¥ï¸
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.2
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies ğŸ”§
              run: npm ci
            - name: Version ğŸ·ï¸
              run: cd projects/kit && npm version ${{ github.event.inputs.version }}
            - name: Build ğŸ—ï¸
              run: npm run build:prod
            - name: Publish ğŸš€
              run: cd dist/kit && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
