name: Code quality
on:
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v3
            - name: Node ğŸ–¥ï¸
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.2
            - name: Install dependencies ğŸ”§
              run: npm ci
            - name: Format ğŸ¨
              run: npm run format:check
            - name: Lint ğŸš¨
              run: npm run lint
